name: Bump kaplayjs/kaplayground submodule

on:
  push:
    branches: master

jobs:
  sync:
    permissions: write-all
    name: "Dispatch Event"
    runs-on: ubuntu-latest
    if: github.repository_owner == 'kaplayjs'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check if there are changes in examples/ folder between HEAD and last commit
        run: |
          git diff --exit-code HEAD^ HEAD -- examples/
          if [ $? -eq 0 ]; then
            echo "No changes in examples/ folder"
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "Changes detected in examples/ folder"
            echo "changes=true" >> $GITHUB_ENV
          fi
      - name: Dispatch Event
        uses: actions/github-script@v6
        if: env.changes == 'true'
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'kaplayjs',
              repo: 'kaplayground',
              workflow_id: 'upgrade-submodules.yml',
              ref: 'main'
            })