name: Bump kaplayjs/kaplayground submodule

on:
  push:
    branches: master

jobs:
  sync:
    permissions: write-all
    name: "Dispatch Event"
    runs-on: ubuntu-latest
    if: github.repository_owner == 'kaplayjs'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check if there are changes in examples/ folder
        id: check_changes
        run: |
          git config --global user.name "Bag Bot"
          git config --global user.email "lajbel@kaplayjs.com"
          git fetch origin master
          git diff --exit-code origin/master -- examples/
          if [ $? -ne 0 ]; then
            echo "Changes detected in examples/ folder."
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "No changes detected in examples/ folder."
            echo "changes=false" >> $GITHUB_ENV
          fi
      - uses: actions/github-script@v6
        if: env.changes == 'true'
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'kaplayjs',
              repo: 'kaplayground',
              workflow_id: 'upgrade-submodules.yml',
              ref: 'main'
            })