name: Test KAPLAY

on:
  push:
    branches: 
      - master
      - v3001
  pull_request:

jobs:
  check-format:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - name: Install dprint
        run: pnpm i dprint
      - name: Run Formatter
        run: pnpm run fmt
      - name: Check if it's formatted
        run: |
          FORMATTED=$(git diff --exit-code)
      - name: Fail if not formatted
        run: |
          if [ -n "$FORMATTED" ]; then
            echo "Code is not formatted. Please run 'pnpm run fmt' to format the code."
            exit 1
          else
            echo "Code is formatted correctly."
          fi
      - name: Comment PR
        if: failure() && github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Hey! Please run `pnpm run fmt` to format the code.
          github-token: ${{ secrets.BOT_TOKEN }}
        
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: check-format
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - name: Install dependencies
        run: pnpm install --ignore-scripts
      - name: Install Chrome for Puppeteer
        run: npx puppeteer browsers install chrome
      - name: Fast build
        run: pnpm run build:fast
      - name: Run checker
        run: pnpm run check
      - name: Run tests
        run: pnpm run test -c
      - name: Run Vitest
        run: pnpm run test:vite
      - name: Upload Package
        if: ${{ github.event_name == 'pull_request' }}
        run: pnpx pkg-pr-new publish

  deploy:
    name: Upload KAPLAY to CDN
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - name: Install dependencies
        run: pnpm install --ignore-scripts
      - name: Build
        run: pnpm run build
      - name: Upload kaplay.js to cdn
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "Uploading kaplay.js to CDN"
          curl https://cdn.kaplayjs.com/kaplay.{{ github.ref_name }}.js -X PUT --header "X-Auth-Key: {{ secrets.CDN_KEY }}" --upload-file ./dist/kaplay.js
          curl https://cdn.kaplayjs.com/kaplay.master.js -X PUT --header "X-Auth-Key: {{ secrets.CDN_KEY }}" --upload-file ./dist/kaplay.js
          curl https://cdn.kaplayjs.com/doc.{{ github.ref_name }}.d.ts -X PUT --header "X-Auth-Key: {{ secrets.CDN_KEY }}" --upload-file ./dist/doc.d.ts
          curl https://cdn.kaplayjs.com/doc.master.d.ts -X PUT --header "X-Auth-Key: {{ secrets.CDN_KEY }}" --upload-file ./dist/doc.d.ts
          curl https://cdn.kaplayjs.com/global.{{ github.ref_name }}.d.ts -X PUT --header "X-Auth-Key: {{ secrets.CDN_KEY }}" --upload-file ./dist/global.d.ts
          curl https://cdn.kaplayjs.com/global.master.d.ts -X PUT --header "X-Auth-Key: {{ secrets.CDN_KEY }}" --upload-file ./dist/global.d.ts
